stages:
  load_data:
    cmd: python src/get_data.py --config=config/params.yaml
    deps:
    - data_given/train
    - data_given/test
  

  train_and_evaluate:
      cmd: python src/train_evaluate.py --config=config/params.yaml
      deps:
      - data_given/train
      - data_given/test

      outs:
      - models
      # metrics:
      # - reports/scores.json:
      #     cache: false

  log_production_model:
      cmd: python src/train_evaluate.py --config=config/params.yaml
      deps:
      - src/log_production_model.py

